-- MySQL Script generated by MySQL Workbench
-- Thu Mar  9 17:23:33 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bank` DEFAULT CHARACTER SET utf8 ;
USE `bank` ;

-- -----------------------------------------------------
-- Table `bank`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`users` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL UNIQUE,
  `password` CHAR(64) NULL,
  `salt` BINARY(16)  NULL,
  `cookies` BINARY(16) NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`balances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`balances` (
  `users_iduser` INT NOT NULL,
  `balances` DOUBLE NOT NULL DEFAULT 0.0,
  PRIMARY KEY (`users_iduser`),
  INDEX `fk_balances_users_idx` (`users_iduser` ASC),
  CONSTRAINT `fk_balances_users`
    FOREIGN KEY (`users_iduser`)
    REFERENCES `bank`.`users` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
